export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// ENGINEER TYPES

// Board
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_TASKS = "GET_USER_TASKS";
export const GET_USER_GRAPH_DETAILS = "GET_USER_GRAPH_DETAILS";

//Tasks

export const GET_TASKS = "GET_TASKS";
export const GET_USER_WEEK = "GET_USER_WEEK";

export const SET_TASK_DONE = "SET_TASK_DONE";
export const SET_TASK_HOLD = "HOLD";
export const CHANGE_TASK_STATUS = "CHANGE_TASK_STATUS";

// TECHNICAL PROJECT MANAGER TYPES
// Board
export const GET_TECHNICAL_PROJECT_MANAGER_BOARD_INFO =
  "GET_TECHNICAL_PROJECT_MANAGER_BOARD_INFO";
export const GET_TECHNICAL_PROJECT_MANAGER_BOARD_WORKPACKAGES =
  "GET_TECHNICAL_PROJECT_MANAGER_WORKPACKAGES";
export const GET_TECHNICAL_PROJECT_MANAGER_BOARD_GRAPH_DETAILS =
  "GET_TECHNICAL_PROJECT_MANAGER_BOARD_GRAPH_DETAILS";

export const GET_WORKPACKAGES = "GET_WORKPACKAGES";
export const CREATE_WORKPACKAGE = "CREATE_WORKPACKAGE";
export const EDIT_WORKPACKAGE = "EDIT_WORKPACKAGE";
export const DELETE_WORKPACKAGE = "DELETE_WORKPACKAGE";
export const GET_LEAD_ENGINEERS = "GET_LEAD_ENGINEERS";

// LEAD ENGINEER TYPES

// Board
export const GET_LEAD_ENGINEER_BOARD_INFO = "GET_LEAD_ENGINEER_BOARD_INFO";
export const GET_LEAD_ENGINEER_BOARD_WORKPACKAGES =
  "GET_LEAD_ENGINEER_BOARD_WORKPACKAGES";
export const GET_LEAD_ENGINEER_BOARD_GRAPH_DETAILS =
  "GET_LEAD_ENGINEER_BOARD_GRAPH_DETAILS";

// WorkPackages
export const GET_LEAD_ENGINEER_WORKPACKAGES = "GET_LEAD_ENGINEER_WORKPACKAGES";
export const ADD_LEAD_ENGINEER_TASK = "ADD_LEAD_ENGINEER_TASK";
export const EDIT_LEAD_ENGINEER_TASK = "EDIT_LEAD_ENGINEER_TASK";
export const DELETE_LEAD_ENGINEER_TASK = "DELETE__LEAD_ENGINEER_TASK";

// TEAM LEADER TYPES

// Board
export const GET_TEAM_LEADER_BOARD_INFO = "GET_TEAM_LEADER_BOARD_INFO";
export const GET_TEAM_LEADER_BOARD_WORKPACKAGES =
  "GET_TEAM_LEADER_BOARD_WORKPACKAGES";
export const GET_TEAM_LEADER_BOARD_GRAPH_DETAILS =
  "GET_TEAM_LEADER_BOARD_GRAPH_DETAILS";

export const GET_COLUMNS = "GET_COLUMNS";
export const GET_WEEK_WITH_TASKS_FOR_TEAM_LEADER =
  "GET_WEEK_WITH_TASKS_FOR_TEAM_LEADER";
export const GET_WEEK_WITH_TASKS_FOR_TEAM_LEADERR =
  "GET_WEEK_WITH_TASKS_FOR_TEAM_LEADER";

export const ASSIGN_TASK = "ASSIGN_TASK";
export const DELETE_FROM_UNFINISHED_TASKS = "DELETE_FROM_UNFINISHED_TASKS";
export const DELETE_FROM_BACKLOG = "DELETE_FROM_BACKLOG";
export const DELETE_FROM_DAY_ID = "DELETE_FROM_DAY_ID";
export const ADD_TO_UNFINISHED_TASKS = "ADD_TO_UNFINISHED_TASKS";
export const ADD_TO_BACKLOG = "ADD_TO_BACKLOG";
export const ADD_TO_DAY_ID = "ADD_TO_DAY_ID";

// ACCOUNT

export const UPLOAD_PICTURE = "UPLOAD_PICTURE";
