export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// ENGINEER TYPES

// Board
export const GET_INFO = "GET_INFO";

export const GET_TASKS = "GET_TASKS";
export const SET_TASK_DONE = "SET_TASK_DONE";
export const SET_TASK_HOLD = "HOLD";
export const CHANGE_TASK_STATUS = "CHANGE_TASK_STATUS";

// TECHNICAL PROJECT MANAGER TYPES
export const CREATE_WORKPACKAGE = "CREATE_WORKPACKAGE";
export const EDIT_WORKPACKAGE = "EDIT_WORKPACKAGE";
export const DELETE_WORKPACKAGE = "DELETE_WORKPACKAGE";

// LEAD ENGINEER TYPES
export const ADD_TASK = "ADD_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
